apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: my-nginx1231
spec:
  containers:
  - image: nginx
    name: nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
