apiVersion: v1
kind: Pod
metadata:
  labels:
    run: nginx
  name: my-nginx1231
  namespace: flux-system
spec:
  containers:
  - image: nginxadfdf
    name: nginx
    resources: {}
  dnsPolicy: ClusterFirst
  restartPolicy: Always
status: {}
